# Inserts a blank line between shell prompts
add_newline = false

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'

[python]
format = '[${pyenv_prefix}python (${version} )(\($virtualenv\) )]($style)'
python_binary = ["./venv/Scripts/python", "python", "python3", "python2"]
detect_extensions = []

[directory]
truncation_length = 10
truncate_to_repo = false # truncates directory to root folder if in github repo
style = "yellow"
format = "[$path]($style)[$lock_symbol]($lock_style) "

[package]
format = "[pkg $version]($style) "
symbol = []

[git_branch]
style = "bold green"
format = '[\(on $branch\)]($style) '

[git_status]
disabled = true
modified = '*'

[git_commit]
commit_hash_length = 7
style = "bold blue"

